baseURL: "https://www.moosy.de/"
title: "Portfolio"
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
languageCode: de-DE
defaultContentLanguage: de
minify:
    disableXML: true
    # minifyOutput: true

languages:
    de:
        languageName: "Deutsch"
        weight: 1
        menu:
            main:
                - name: Meine Software
                  url: https://www.telefonbucheditor.de
                  weight: 5

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "My own space on the Internet"
    author: Felix Golatofski
    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false

    profileMode:
        enabled: true
        title: "Michael Moosbauer" # optional default will be site title
        imageUrl: "/images/avatar.png" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size

    socialIcons: # optional
        - name: "GitHub"
          url: "https://github.com/moosy"
        - name: "eMail"
          url: "mailto:info@michael-moosbauer.de"
        - name: "Instagram"
          url: "https://www.instagram.com/michaelmoosbauer"

markup:
    goldmark:
        renderer:
            unsafe: true

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true